name: Update Proseka Data

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz deepl python-dotenv
    
    - name: Run all updates
      env:
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: python app.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.json
        git diff --staged --quiet || git commit -m "Update game data $(date +%Y-%m-%d-%H:%M)"
        git push